### ISSUE TITLE
Unable to enter the toolbox shell with 'toolbox enter'

### ISSUE THREAD

**Issue by g7fernandes** [kubic-project/microos-toolbox#13]
I'm using OpenSUSE Leap 15.2, and I installed toolbox with zypper. I could create the toolbox container with `toolbox create`, but the `enter` command finds nothing in the path. 
I also downloaded a MicroOS image and installed in a VM. The same error appears. 

```
gabriel@localhost:~> toolbox enter
Container 'toolbox-gabriel' already exists. Trying to start...
(To remove the container and start with a fresh toolbox, run: podman rm 'toolbox-gabriel')
Container started successfully. To exit, type 'exit'.
Error: exec failed: container_linux.go:349: starting container process caused "exec: \"enter\": executable file not found in $PATH": OCI runtime command not found error
```
Running `toolbox -u` works to enter the shell.

**Comment by thkukuk** [comment]
As even Tumbleweed and MicroOS do not support `enter` yet, I would be surprised if Leap would support it.
You should check at first which commands the installed toolbox supports before trying random commands.

**Comment by marcosps** [comment]
> As even Tumbleweed and MicroOS do not support `enter` yet, I would be surprised if Leap would support it.

@thkukuk I also tried to run toolbox enter by following a [blog post](https://kalikiana.gitlab.io/post/2021-02-22-developing-in-toolbox-containers/), and it also failed as you stated.  But I managed to find this issue and tried the -u option :)

> You should check at first which commands the installed toolbox supports before trying random commands.
I believe that you could be more kind to a user trying to use the software you help to create/maintain, instead of telling them to not 'try random commands'.

**Comment by g7fernandes** [comment]
@marcosps
Now I'm using the toolbox that is available for OpenSUSE TW and it has `enter` implemented. The `enter` command cannot be used with the `-c` problem due [this issue](https://github.com/kubic-project/microos-toolbox/issues/19).

**Comment by marcosps** [comment]
@g7fernandes great news, as I'm currently using Leap, I'll wait more time before trying to user _enter_ again :)

**Comment by dfaggioli** [comment]
> @marcosps
> Now I'm using the toolbox that is available for OpenSUSE TW and it has `enter` implemented. When I opened this issue, there were instructions on the README.md of this project to use the `enter` command before it was implemented.
> 
No, the changes to the README, here on GitHub, were made as part of the same patch series that implemented `create`, `enter`, etc. The problem you faced was that this new UI is both implemented and documented here, but the package that you install with `zypper in toolbox`, most likely, was not updated to the latest version that we have here yet.

So, it is indeed the case that one shouldn't mix and match docs from the GitHub project and from the package. Basically, the README of the toolbox installed with zypper is to be found in `/usr/share/doc/packages/toolbox/README.md` (at least in TW... in MicroOS, well, not really, as we don't install docs by default).

I think we should also make a proper manpage (carving it out of the README file, perhaps). Again, that would only help on TW, but it's already something.

> Still, the `enter` command cannot be used with the `-c` option problem due [this issue](https://github.com/kubic-project/microos-toolbox/issues/19). But it is easy to solve.
>
Ok, just seen your other issue. Thanks for reporting. I'll work on a patch :-)
