### ISSUE TITLE
Make toolbox work out of the box

### ISSUE THREAD

**Issue by kalikiana** [kubic-project/microos-toolbox#18]
# Problem

So, I just tried to confirm this on a Tumbleweed install. Getting toolbox from repos, no custom configuration here. And attempting to just run toolbox w/o any arguments.

This is what I get even if I follow the proper docs showcasing how to run toolbox. I did *not* scroll all the way to the *Troubleshooting* section at this point.

It would be really nice if the default experience could be nicer. Because so many people run into this. And for the sake of this issue, please pretend I'm a **new user who doesn't even know why this explodes** the way it does 😉 

# Full log

```bash
$ sudo zypper in toolbox
[sudo] password for root: 
Retrieving repository 'openSUSE-Tumbleweed-Non-Oss' metadata .............[done]
Building repository 'openSUSE-Tumbleweed-Non-Oss' cache ..................[done]
Retrieving repository 'openSUSE-Tumbleweed-Oss' metadata .................[done]
Building repository 'openSUSE-Tumbleweed-Oss' cache ......................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  toolbox

1 new package to install.
Overall download size: 21,5 KiB. Already cached: 0 B. After the operation,
additional 38,4 KiB will be used.
Continue? [y/n/v/...? shows all options] (y): 
Retrieving package toolbox-2.1+git20210203.a669e3a-1.1.noarch
                                           (1/1),  21,5 KiB ( 38,4 KiB unpacked)
Retrieving: toolbox-2.1+git20210203.a669e3a-1.1.noarch.rpm ...............[done]

Checking for file conflicts: .............................................[done]
(1/1) Installing: toolbox-2.1+git20210203.a669e3a-1.1.noarch .............[done]
$ toolbox
Trying to pull registry.opensuse.org/opensuse/toolbox:latest...
Getting image source signatures
Copying blob 4541e5915704 done  
Copying blob 15a56f443a36 done  
Copying config 6104b478cc done  
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:15 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
Error: Error committing the finished image: error adding layer with blob "sha256:4541e5915704d5e8c380446e70d1bcc509811a6b1645fb91f32a7045c21cd65d": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:15 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
```
# Suggestion

- Have *toolbox* do something like `grep $USER /etc/sub{u,g}id` and prompt the user to add the required lines to those two files, or elevate to do it automatically.
- Run `sudo usermod --add-subuids 200000-201000 --add-subgids 200000-201000 $USER` automatically

**Comment by dfaggioli** [comment]
> # Suggestion
> * Have _toolbox_ do something like `grep $USER /etc/sub{u,g}id` and prompt the user to add the required lines to those two files, or elevate to do it automatically.
>
Yes, this makes sense, and can be done quite easily, I think.

> * Run `sudo usermod --add-subuids 200000-201000 --add-subgids 200000-201000 $USER` automatically
>
This is trickier. In fact, even if we do it. The user should still reboot (well, technically not necessarily reboot, but just logout & religion does not work. It's been reported that `loginctl kill-session $MY_SESSION_ID`, and then relogin does... but rebooting is probably easier).

**Comment by thkukuk** [comment]
>     * Run `sudo usermod --add-subuids 200000-201000 --add-subgids 200000-201000 $USER` automatically

We cannot use static UIDs and GIDs, but we would need to parse configuration files to find the correct numbers for this system. I think the current, new hint that this entries are missing and how to create them is good enough. Tools shouldn't be too clever and try to automatically fix things, could be that they do more harm then use with this and the admin cannot even prevent this.

So I'm closing this.

**Comment by kalikiana** [comment]
Speaking purely from the user story... I can't say that one would ever care about those numbers. But this is a big improvement and addresses the confusion I've seen when people ran into it. So thank you for addressing this issue.
