### ISSUE TITLE
Script exits when using -c even if no option -t is given complaining about -c and -t not being allowed together

### ISSUE THREAD

**Issue by g7fernandes** [kubic-project/microos-toolbox#19]
When the container name is given, it checks if there **is** something assigned to `TAG` to check if the option `-t` was used. However, something is assigned to `TAG` when the `-t` is used. The `-z` should be a `-n`.

```bash
            -c|--container)
                if [ -z "$TAG" ]; then
                    echo "ERROR: Don't use both -c and -t!"
                    show_help
                    exit 1
                fi
                CHANGE_NAME="true"
                TOOLBOX_NAME="$2"
                shift 2
                ;;
```

https://github.com/kubic-project/microos-toolbox/blob/a720b251d2e23c312aa02b9ada77649eb9e4481b/toolbox#L285

**Comment by jlausuch** [comment]
I have observed the same behaviour.

**Comment by thkukuk** [comment]
Should be fixed now.
