### ISSUE TITLE
Consider switching to containers/toolbox?

### ISSUE THREAD

**Issue by tudurom** [kubic-project/microos-toolbox#5]
[containers/toolbox](https://github.com/containers/toolbox) has more features and is better integrated with the host system than this one, and they intend to support more distros than just Fedora. I have just submitted two issues to make it work perfectly with openSUSE toolbox images.

**Comment by thkukuk** [comment]
The last time I looked at containers/toolbox it had many, many hardcoded "fedora" in it. Yes, somehow you can get it working on other distros, but not really user-friendly out-of-the-box. And "intend" does not mean it supports it. Reading the documentation shows more the opposite, it's still very RedHat/Fedora centric.
